In [32]:
import pandas as pd
import json
import urllib.request as url
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [2]:
path = "https://api.covid19india.org/states_daily.json"
response = url.urlopen(path)
data = json.load(response)

In [3]:
df = pd.DataFrame(data['states_daily'])

In [4]:
df.shape

(1563, 42)

In [5]:
df.head()

an ap ar as br ch ct       date     dateymd dd  ... sk     status tg tn tr  \
0  0  1  0  0  0  0  0  14-Mar-20  2020-03-14  0  ...  0  Confirmed  1  1  0   
1  0  0  0  0  0  0  0  14-Mar-20  2020-03-14  0  ...  0  Recovered  0  0  0   
2  0  0  0  0  0  0  0  14-Mar-20  2020-03-14  0  ...  0   Deceased  0  0  0   
3  0  0  0  0  0  0  0  15-Mar-20  2020-03-15  0  ...  0  Confirmed  2  0  0   
4  0  0  0  0  0  0  0  15-Mar-20  2020-03-15  0  ...  0  Recovered  1  0  0   

   tt un  up ut wb  
0  81  0  12  0  0  
1   9  0   4  0  0  
2   2  0   0  0  0  
3  27  0   1  0  0  
4   4  0   0  0  0  

[5 rows x 42 columns]

In [6]:
confirmed_df = df[df['status'] == 'Confirmed']

In [18]:
total_cases = confirmed_df['tt']
total_cases = total_cases.astype('int')

In [19]:
total_cases[:10]

0      81
3      27
6      15
9      11
12     37
15     27
18     58
21     78
24     67
27    102
Name: tt, dtype: int32

In [20]:
total_cases = total_cases.values
X = []
y = []
start = 0
stop = 5
for i in range(len(total_cases) - 5):
    X.append(total_cases[start:stop])
    y.append(total_cases[stop])
    start += 1
    stop += 1

In [21]:
X[:5]

[array([81, 27, 15, 11, 37]),
 array([27, 15, 11, 37, 27]),
 array([15, 11, 37, 27, 58]),
 array([11, 37, 27, 58, 78]),
 array([37, 27, 58, 78, 67])]

In [22]:
y[:5]

[27, 58, 78, 67, 102]

In [33]:
minmax = MinMaxScaler()

In [34]:
X_scaled = minmax.fit_transform(X)

In [35]:
y = np.asarray(y)
y_scaled = minmax.fit_transform(y.reshape(-1,1))

In [36]:
y_scaled[:5]

array([[0.00000000e+00],
       [7.48334955e-05],
       [1.23113170e-04],
       [9.65593490e-05],
       [1.81048779e-04]])

In [37]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [38]:
regerssion = LinearRegression()
regerssion.fit(x_train, y_train)

LinearRegression()

In [39]:
y_pred = regerssion.predict(x_test)

In [40]:
mean_squared_error(y_test, y_pred)

43100591.99370249

In [41]:
np.sqrt(mean_squared_error(y_test, y_pred))

6565.104111413809

In [42]:
y[:5]

array([ 27,  58,  78,  67, 102])

In [43]:
y_pred[:5]

array([50480.00138816, 13743.58394868, 91950.14896625, 69175.59829891,
       50782.69671938])