In [1]:
import pickle as pkl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv('Madedata1.csv')

In [3]:
df.shape

(2499, 12)

In [4]:
df.head()

Country  Age       Gender  fever  Bodypain  Runny_nose  \
0               China   10         Male    102         1           0   
1               Italy   20         Male    103         1           1   
2                Iran   55  Transgender     99         0           0   
3  Republic of Korean   37       Female    100         0           1   
4              France   45         Male    101         1           1   

   Difficulty_in_breathing  Nasal_congestion  Sore_throat  Severity  \
0                        0                 0            1      Mild   
1                        0                 0            0  Moderate   
2                        0                 1            1    Severe   
3                        1                 0            0      Mild   
4                        1                 1            0  Moderate   

  Contact_with_covid_patient  Infected  
0                         No         0  
1                  Not known         1  
2                         No         0  
3                        Yes         1  
4                        Yes         1

In [5]:
# checking for missing values in data
df.isna().sum()

Country                       0
Age                           0
Gender                        0
fever                         0
Bodypain                      0
Runny_nose                    0
Difficulty_in_breathing       0
Nasal_congestion              0
Sore_throat                   0
Severity                      0
Contact_with_covid_patient    0
Infected                      0
dtype: int64

In [6]:
pd.value_counts(df['Gender'])

Male           1257
Female         1208
Transgender      34
Name: Gender, dtype: int64

In [7]:
pd.value_counts(df['Severity'])

Mild        1591
Moderate     525
Severe       383
Name: Severity, dtype: int64

In [8]:
pd.value_counts(df['Contact_with_covid_patient'])

No           1203
Yes           638
Not known     633
yes            25
Name: Contact_with_covid_patient, dtype: int64

In [9]:
df['Contact_with_covid_patient'] = df['Contact_with_covid_patient'].str.lower()

In [10]:
pd.value_counts(df['Contact_with_covid_patient'])

no           1203
yes           663
not known     633
Name: Contact_with_covid_patient, dtype: int64

In [11]:
gender = df['Gender']

genderLabel = LabelEncoder()
gender = genderLabel.fit_transform(df['Gender'])

In [12]:
gender

array([1, 1, 2, ..., 0, 0, 0])

In [16]:
genderOneHot = OneHotEncoder()
gender = genderOneHot.fit_transform(gender.reshape(-1,1)).toarray()

In [17]:
gender

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [18]:
severity = df['Severity']

severityLabel = LabelEncoder()
severity = severityLabel.fit_transform(severity)

severityOneHot = OneHotEncoder()
severity = severityOneHot.fit_transform(severity.reshape(-1,1)).toarray()

In [19]:
contact = df['Contact_with_covid_patient']

contactLabel = LabelEncoder()
contact = contactLabel.fit_transform(contact)

contactOneHot = OneHotEncoder()
contact = contactOneHot.fit_transform(contact.reshape(-1,1)).toarray()

In [20]:
severity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [21]:
contact

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
df.drop(columns=['Country','Gender','Severity','Contact_with_covid_patient'],
       inplace=True)

In [23]:
df.head()

Age  fever  Bodypain  Runny_nose  Difficulty_in_breathing  \
0   10    102         1           0                        0   
1   20    103         1           1                        0   
2   55     99         0           0                        0   
3   37    100         0           1                        1   
4   45    101         1           1                        1   

   Nasal_congestion  Sore_throat  Infected  
0                 0            1         0  
1                 0            0         1  
2                 1            1         0  
3                 0            0         1  
4                 1            0         1

In [24]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [25]:
X = np.c_[X, gender, severity, contact]

In [26]:
X[0]

array([ 10., 102.,   1.,   0.,   0.,   0.,   1.,   0.,   1.,   0.,   1.,
         0.,   0.,   1.,   0.,   0.])