In [1]:
import numpy as np

In [2]:
np.array([3,4,5,4,3,5])

array([3, 4, 5, 4, 3, 5])

In [3]:
np.array([[3,2,3,4],[32,3,5,56],[3,5,6,8],[1,2,3,5]])

array([[ 3,  2,  3,  4],
       [32,  3,  5, 56],
       [ 3,  5,  6,  8],
       [ 1,  2,  3,  5]])

In [4]:
np.array([2,3,4,5.6,4,5,6])

array([2. , 3. , 4. , 5.6, 4. , 5. , 6. ])

In [5]:
np.array([2,3,4,5.6,4,5,6,'10'])

array(['2', '3', '4', '5.6', '4', '5', '6', '10'], dtype='<U32')

In [6]:
np.array([31,2,3,5,7,6,True,4.5])

array([31. ,  2. ,  3. ,  5. ,  7. ,  6. ,  1. ,  4.5])

In [7]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
#linear space
# returns 50 elements b/w the given range with equal interval
# np.linspace(1,12)

np.linspace(1,12,num=18,retstep=True)

(array([ 1.        ,  1.64705882,  2.29411765,  2.94117647,  3.58823529,
         4.23529412,  4.88235294,  5.52941176,  6.17647059,  6.82352941,
         7.47058824,  8.11764706,  8.76470588,  9.41176471, 10.05882353,
        10.70588235, 11.35294118, 12.        ]),
 0.6470588235294118)

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones([5,5]) * 6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.random()

0.5206153136662761

In [23]:
np.random.random(5)

array([0.45421872, 0.68829641, 0.33946783, 0.85110276, 0.73733929])

In [24]:
np.random.random([4,5])

array([[0.92831283, 0.10440347, 0.00380531, 0.45786187, 0.22023108],
       [0.24307022, 0.80071627, 0.17599536, 0.97032638, 0.52270066],
       [0.4578654 , 0.04277973, 0.76420414, 0.13279454, 0.0121871 ],
       [0.58918086, 0.70743013, 0.98197273, 0.2437788 , 0.28551079]])

In [25]:
np.random.randint(1,100)

26

In [26]:
np.random.randint(1,100,10)

array([21, 61, 26, 96, 62, 72,  5, 53, 86, 85])

In [27]:
np.random.randint(1,100,[5,8])

array([[81, 65, 90, 39, 99, 75, 21, 72],
       [68, 60, 14, 67, 44, 18, 24, 20],
       [85, 55, 63, 98, 97, 91, 35, 34],
       [13, 53, 77, 73,  4, 37, 76, 27],
       [84, 14, 88, 38, 99, 93, 54, 12]])