In [1]:
import numpy as np

In [2]:
x = np.array([[1,0,1,0], [1,0,1,1], [0,1,0,1]])
y = np.array([[1],[1],[0]])

In [3]:
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
y

array([[1],
       [1],
       [0]])

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivativeSigmoid(x):
    return x * (1 - x)

In [22]:
inputNeurons = x.shape[1]
hiddenNeurons = 3
outputNeurons = 1
alpha = 0.01

In [7]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1, hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1, outputNeurons))

In [8]:
# feedforward
# 1. xi.wi + bias
fx = np.dot(x, weightsHidden) + biasHidden

In [9]:
fx

array([[1.73693259, 2.25819832, 2.09886788],
       [2.40443048, 2.78679369, 2.90919876],
       [1.16135179, 2.01248692, 2.0302972 ]])

In [10]:
# 2. Apply Activation
hiddenLayer = sigmoid(fx)

In [11]:
hiddenLayer

array([[0.85029703, 0.90535536, 0.89079309],
       [0.91716453, 0.94195799, 0.9482993 ],
       [0.76157826, 0.8821019 , 0.88394157]])

In [12]:
# 3. zi.wi + bias
fx1 = np.dot(hiddenLayer, weightsOutput) + biasOutput

In [13]:
fx1

array([[1.44450914],
       [1.47454642],
       [1.42218875]])

In [14]:
# 4. Apply activation on output
output = sigmoid(fx1)

In [15]:
output

array([[0.80915195],
       [0.81374744],
       [0.80568131]])

In [16]:
# Backpropagation
# Error
# Slope
# Delta

errorOutput = output - y

In [17]:
errorOutput

array([[-0.19084805],
       [-0.18625256],
       [ 0.80568131]])

In [18]:
slopeOutput = derivativeSigmoid(output)
deltaOutput = errorOutput * slopeOutput

In [20]:
errorHidden = np.dot(deltaOutput, weightsOutput.T)

In [21]:
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden

In [24]:
weightsOutput = weightsOutput - hiddenLayer.T.dot(deltaOutput) * alpha
weightsHidden = weightsHidden - x.T.dot(deltaHidden) * alpha
biasOutput = biasOutput - np.sum(deltaOutput) * alpha
biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [31]:
epochs = 50000

weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1, hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1, outputNeurons))

for i in range(epochs):
    # Feedforward
    fx = np.dot(x, weightsHidden) + biasHidden
    hiddenLayer = sigmoid(fx)
    fx1 = np.dot(hiddenLayer, weightsOutput) + biasOutput
    output = sigmoid(fx1)
    
    # Backpropagation
    errorOutput = output - y
    slopeOutput = derivativeSigmoid(output)
    deltaOutput = errorOutput * slopeOutput
    
    errorHidden = np.dot(deltaOutput, weightsOutput.T)
    slopeHidden = derivativeSigmoid(hiddenLayer)
    deltaHidden = errorHidden * slopeHidden
    
    weightsOutput = weightsOutput - hiddenLayer.T.dot(deltaOutput) * alpha
    weightsHidden = weightsHidden - x.T.dot(deltaHidden) * alpha
    biasOutput = biasOutput - np.sum(deltaOutput) * alpha
    biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [32]:
output

array([[0.97890822],
       [0.97019839],
       [0.05167442]])

In [33]:
errorOutput

array([[-0.02109178],
       [-0.02980161],
       [ 0.05167442]])