In [9]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
df = pd.read_csv('full_data.csv')

In [3]:
df.shape

(4981, 11)

In [4]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1

In [8]:
tf.unique(df['gender'])

Unique(y=<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Male', b'Female'], dtype=object)>, idx=<tf.Tensor: shape=(4981,), dtype=int32, numpy=array([0, 0, 1, ..., 1, 0, 1])>)

In [10]:
np.unique(df['gender'])

array(['Female', 'Male'], dtype=object)

In [11]:
np.unique(df['ever_married'])

array(['No', 'Yes'], dtype=object)

In [12]:
np.unique(df['work_type'])

array(['Govt_job', 'Private', 'Self-employed', 'children'], dtype=object)

In [13]:
np.unique(df['Residence_type'])

array(['Rural', 'Urban'], dtype=object)

In [14]:
np.unique(df['smoking_status'])

array(['Unknown', 'formerly smoked', 'never smoked', 'smokes'],
      dtype=object)

In [36]:
layer = tf.keras.layers.CategoryEncoding(num_tokens=4, output_mode='one_hot')

In [37]:
layer([0,1,2,3])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [38]:
from sklearn.preprocessing import LabelEncoder

In [39]:
label = LabelEncoder()
df['gender'] = label.fit_transform(df['gender'])
df['ever_married'] = label.fit_transform(df['ever_married'])
df['work_type'] = label.fit_transform(df['work_type'])
df['Residence_type'] = label.fit_transform(df['Residence_type'])
df['smoking_status'] = label.fit_transform(df['smoking_status'])

In [31]:
layer(df['smoking_status'])

<tf.Tensor: shape=(4981, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

In [40]:
layer(df['work_type'])

<tf.Tensor: shape=(4981, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [41]:
layer = tf.keras.layers.CategoryEncoding(num_tokens=2, output_mode='one_hot')
layer(df['gender'])

<tf.Tensor: shape=(4981, 2), dtype=float32, numpy=
array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)>

In [42]:
layer(df['ever_married'])

<tf.Tensor: shape=(4981, 2), dtype=float32, numpy=
array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)>

In [43]:
layer(df['Residence_type'])

<tf.Tensor: shape=(4981, 2), dtype=float32, numpy=
array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)>

In [53]:
layer_1 = tf.keras.layers.CategoryEncoding(num_tokens=4, output_mode='one_hot')
layer_2 = tf.keras.layers.CategoryEncoding(num_tokens=2, output_mode='one_hot')

In [58]:
cols = tf.concat([layer_1(df['smoking_status']), layer_1(df['work_type']), 
          layer_2(df['gender']), layer_2(df['ever_married']), layer_2(df['Residence_type'])], 1)

In [59]:
cols.shape

TensorShape([4981, 14])

In [60]:
X = df.iloc[:,:-1]
y = df.iloc[:, -1]

In [61]:
X.drop(columns=['gender','smoking_status','work_type','ever_married','Residence_type'], inplace=True)

In [62]:
X.head()

age  hypertension  heart_disease  avg_glucose_level   bmi
0  67.0             0              1             228.69  36.6
1  80.0             0              1             105.92  32.5
2  49.0             0              0             171.23  34.4
3  79.0             1              0             174.12  24.0
4  81.0             0              0             186.21  29.0

In [65]:
x_data = tf.concat([X.values, cols], 1)

In [66]:
x_data[0]

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([ 67.  ,   0.  ,   1.  , 228.69,  36.6 ,   0.  ,   1.  ,   0.  ,
         0.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         1.  ,   0.  ,   1.  ], dtype=float32)>

In [67]:
from sklearn.model_selection import train_test_split

In [69]:
x_data.shape

TensorShape([4981, 19])

In [70]:
y[:5]

0    1
1    1
2    1
3    1
4    1
Name: stroke, dtype: int64

In [72]:
type(x_data)

tensorflow.python.framework.ops.EagerTensor

In [74]:
x_data = x_data.numpy()

In [75]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y, test_size=0.25)

In [79]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(19, activation='relu'))
model.add(tf.keras.layers.Dense(38, activation='relu'))
model.add(tf.keras.layers.Dense(45, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [80]:
model.compile(optimizer='adam', loss=tf.keras.losses.BinaryCrossentropy(), metrics=['accuracy'])
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5)

Epoch 1/5
117/117 [==============================] - 1s 2ms/step - loss: 0.3030 - accuracy: 0.9475 - val_loss: 0.1721 - val_accuracy: 0.9583
Epoch 2/5
117/117 [==============================] - 0s 1ms/step - loss: 0.2107 - accuracy: 0.9446 - val_loss: 0.1792 - val_accuracy: 0.9575
Epoch 3/5
117/117 [==============================] - 0s 2ms/step - loss: 0.1993 - accuracy: 0.9467 - val_loss: 0.1654 - val_accuracy: 0.9567
Epoch 4/5
117/117 [==============================] - 0s 1ms/step - loss: 0.1981 - accuracy: 0.9454 - val_loss: 0.1590 - val_accuracy: 0.9583
Epoch 5/5
117/117 [==============================] - 0s 1ms/step - loss: 0.1922 - accuracy: 0.9475 - val_loss: 0.1681 - val_accuracy: 0.9583


In [81]:
# model.predict()

In [82]:
model.history.history

{'loss': [0.3030132055282593,
  0.21074874699115753,
  0.19929881393909454,
  0.19813160598278046,
  0.1921575516462326],
 'accuracy': [0.9475234150886536,
  0.9445782899856567,
  0.9467202425003052,
  0.9453815221786499,
  0.9475234150886536],
 'val_loss': [0.17211979627609253,
  0.17919550836086273,
  0.16538554430007935,
  0.15904852747917175,
  0.16809073090553284],
 'val_accuracy': [0.9582664370536804,
  0.9574638605117798,
  0.9566613435745239,
  0.9582664370536804,
  0.9582664370536804]}

In [83]:
acc = tf.metrics.Accuracy()

In [84]:
# acc.update_state(y_test, y_pred)

In [86]:
model.evaluate(x_test,y_test)

39/39 [==============================] - 0s 605us/step - loss: 0.1681 - accuracy: 0.9583


[0.16809073090553284, 0.9582664370536804]