In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,100,24)

In [3]:
x

array([58, 89, 31, 19, 70, 66, 40, 38,  1, 45, 35, 98, 15, 89, 95, 27, 34,
       23, 41, 57, 54, 51, 91, 28])

In [4]:
x[0]

58

In [5]:
x[0:12]

array([58, 89, 31, 19, 70, 66, 40, 38,  1, 45, 35, 98])

In [6]:
x[-1]

28

In [7]:
x[0:20:2]

array([58, 31, 70, 40,  1, 35, 15, 95, 34, 41])

In [8]:
x = np.random.randint(1,100,[6,4])

In [9]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [10]:
x[0]

array([33, 37, 42, 25])

In [11]:
x[4]

array([ 2, 22, 78, 54])

In [12]:
x[0][0]

33

In [14]:
x[3][2]

27

In [17]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [16]:
x[:, 2]

array([42, 16, 66, 27, 78, 83])

In [18]:
x[:,2:3]

array([[42],
       [16],
       [66],
       [27],
       [78],
       [83]])

In [19]:
x[2:4, 0:3]

array([[30, 42, 66],
       [35, 89, 27]])

In [22]:
x[0:3, [0,2,3]]

array([[33, 42, 25],
       [ 5, 16, 26],
       [30, 66, 61]])

In [25]:
x[[0,3,5], 0:3]

array([[33, 37, 42],
       [35, 89, 27],
       [61, 93, 83]])

In [26]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [27]:
x.shape

(6, 4)

In [28]:
x.ndim

2

In [29]:
# transpose of array
x.T

array([[33,  5, 30, 35,  2, 61],
       [37, 76, 42, 89, 22, 93],
       [42, 16, 66, 27, 78, 83],
       [25, 26, 61, 32, 54, 94]])

In [30]:
x.reshape(2,12)

array([[33, 37, 42, 25,  5, 76, 16, 26, 30, 42, 66, 61],
       [35, 89, 27, 32,  2, 22, 78, 54, 61, 93, 83, 94]])

In [31]:
x.reshape(3,8)

array([[33, 37, 42, 25,  5, 76, 16, 26],
       [30, 42, 66, 61, 35, 89, 27, 32],
       [ 2, 22, 78, 54, 61, 93, 83, 94]])

In [32]:
x.reshape(8,-1)

array([[33, 37, 42],
       [25,  5, 76],
       [16, 26, 30],
       [42, 66, 61],
       [35, 89, 27],
       [32,  2, 22],
       [78, 54, 61],
       [93, 83, 94]])

In [33]:
x.reshape(-1,6)

array([[33, 37, 42, 25,  5, 76],
       [16, 26, 30, 42, 66, 61],
       [35, 89, 27, 32,  2, 22],
       [78, 54, 61, 93, 83, 94]])

In [34]:
# convert n-dimensional to 1D array
x.flatten()

array([33, 37, 42, 25,  5, 76, 16, 26, 30, 42, 66, 61, 35, 89, 27, 32,  2,
       22, 78, 54, 61, 93, 83, 94])

In [35]:
x = x.flatten()

In [36]:
x

array([33, 37, 42, 25,  5, 76, 16, 26, 30, 42, 66, 61, 35, 89, 27, 32,  2,
       22, 78, 54, 61, 93, 83, 94])

In [37]:
np.sum(x)

1129

In [38]:
np.min(x)

2

In [39]:
np.max(x)

94

In [40]:
np.mean(x)

47.041666666666664

In [41]:
np.std(x)

27.15154870761928

In [42]:
np.var(x)

737.2065972222222

In [43]:
np.median(x)

39.5

In [44]:
x = x.reshape(6,4)

In [45]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [46]:
np.sum(x)

1129

In [48]:
# if axis = 0, then perform operation on columns
# if axis = 1, then perform operation on rows
np.sum(x,axis=0)

array([166, 359, 312, 292])

In [49]:
np.sum(x,axis=1)

array([137, 123, 199, 183, 156, 331])

In [50]:
np.mean(x, axis=0)

array([27.66666667, 59.83333333, 52.        , 48.66666667])

In [51]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [52]:
row = np.array([12,22,11,4])

In [53]:
np.vstack((x,row))

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94],
       [12, 22, 11,  4]])

In [55]:
col = np.array([[12],[11],[12],[4],[5],[5]])

In [56]:
np.hstack((x, col))

array([[33, 37, 42, 25, 12],
       [ 5, 76, 16, 26, 11],
       [30, 42, 66, 61, 12],
       [35, 89, 27, 32,  4],
       [ 2, 22, 78, 54,  5],
       [61, 93, 83, 94,  5]])

In [57]:
y = np.hstack((x, col))

In [58]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [59]:
y

array([[33, 37, 42, 25, 12],
       [ 5, 76, 16, 26, 11],
       [30, 42, 66, 61, 12],
       [35, 89, 27, 32,  4],
       [ 2, 22, 78, 54,  5],
       [61, 93, 83, 94,  5]])

In [61]:
x + 5

array([[38, 42, 47, 30],
       [10, 81, 21, 31],
       [35, 47, 71, 66],
       [40, 94, 32, 37],
       [ 7, 27, 83, 59],
       [66, 98, 88, 99]])

In [63]:
y = x * 4

In [64]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [65]:
y

array([[132, 148, 168, 100],
       [ 20, 304,  64, 104],
       [120, 168, 264, 244],
       [140, 356, 108, 128],
       [  8,  88, 312, 216],
       [244, 372, 332, 376]])

In [66]:
x + y

array([[165, 185, 210, 125],
       [ 25, 380,  80, 130],
       [150, 210, 330, 305],
       [175, 445, 135, 160],
       [ 10, 110, 390, 270],
       [305, 465, 415, 470]])

In [69]:
# np.concatenate([x,y])

In [70]:
np.concatenate([x,y], axis=0)

array([[ 33,  37,  42,  25],
       [  5,  76,  16,  26],
       [ 30,  42,  66,  61],
       [ 35,  89,  27,  32],
       [  2,  22,  78,  54],
       [ 61,  93,  83,  94],
       [132, 148, 168, 100],
       [ 20, 304,  64, 104],
       [120, 168, 264, 244],
       [140, 356, 108, 128],
       [  8,  88, 312, 216],
       [244, 372, 332, 376]])

In [71]:
np.concatenate([x,y], axis=1)

array([[ 33,  37,  42,  25, 132, 148, 168, 100],
       [  5,  76,  16,  26,  20, 304,  64, 104],
       [ 30,  42,  66,  61, 120, 168, 264, 244],
       [ 35,  89,  27,  32, 140, 356, 108, 128],
       [  2,  22,  78,  54,   8,  88, 312, 216],
       [ 61,  93,  83,  94, 244, 372, 332, 376]])

In [72]:
np.c_[x,col]

array([[33, 37, 42, 25, 12],
       [ 5, 76, 16, 26, 11],
       [30, 42, 66, 61, 12],
       [35, 89, 27, 32,  4],
       [ 2, 22, 78, 54,  5],
       [61, 93, 83, 94,  5]])

In [78]:
np.r_[x,[[12,22,12,4]]]

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94],
       [12, 22, 12,  4]])

In [79]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [80]:
x > 25

array([[ True,  True,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [81]:
x[x > 25]

array([33, 37, 42, 76, 26, 30, 42, 66, 61, 35, 89, 27, 32, 78, 54, 61, 93,
       83, 94])

In [83]:
(x > 50) | (x < 25)

array([[False, False, False, False],
       [ True,  True,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [84]:
x[(x > 50) | (x < 25)]

array([ 5, 76, 16, 66, 61, 89,  2, 22, 78, 54, 61, 93, 83, 94])

In [86]:
(x % 2 == 0) & (x % 3 == 0)

array([[False, False,  True, False],
       [False, False, False, False],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [85]:
x[(x % 2 == 0) & (x % 3 == 0)]

array([42, 30, 42, 66, 78, 54])

In [88]:
x

array([[33, 37, 42, 25],
       [ 5, 76, 16, 26],
       [30, 42, 66, 61],
       [35, 89, 27, 32],
       [ 2, 22, 78, 54],
       [61, 93, 83, 94]])

In [87]:
np.where(x % 2 == 0)

(array([0, 1, 1, 1, 2, 2, 2, 3, 4, 4, 4, 4, 5], dtype=int64),
 array([2, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 3], dtype=int64))

In [91]:
np.where(x % 2 == 0, 100,10)

array([[ 10,  10, 100,  10],
       [ 10, 100, 100, 100],
       [100, 100, 100,  10],
       [ 10,  10,  10, 100],
       [100, 100, 100, 100],
       [ 10,  10,  10, 100]])