In [1]:
import h5py
import numpy as np

In [2]:
with h5py.File('3d_cnn/full_dataset_vectors.h5','r') as dataset:
    x_train, x_test = dataset["X_train"][:], dataset["X_test"][:]
    y_train, y_test = dataset["y_train"][:], dataset["y_test"][:]

In [3]:
x_train.shape

(10000, 4096)

In [4]:
x_train[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [7]:
16 ** 3

4096

In [19]:
y_train[:10]

array([5, 5, 0, 0, 4, 4, 1, 1, 9, 9], dtype=int64)

In [9]:
type(x_train)

numpy.ndarray

In [10]:
x_train = x_train.reshape(x_train.shape[0], 16,16,16,1)
x_test = x_test.reshape(x_test.shape[0], 16,16,16,1)

In [11]:
x_train.shape

(10000, 16, 16, 16, 1)

In [20]:
import tensorflow as tf
from tensorflow.keras.layers import Conv3D, MaxPool3D, Dense, Flatten
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

In [21]:
y_train = to_categorical(y_train)

In [22]:
y_test = to_categorical(y_test)

In [23]:
y_train[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [24]:
model = Sequential()
model.add(Conv3D(32, (3,3,3), activation="relu", input_shape=(16,16,16,1)))
model.add(Conv3D(32, (3,3,3), activation="relu"))
model.add(MaxPool3D())
model.add(Conv3D(32, (3,3,3), activation="relu"))
model.add(MaxPool3D())
model.add(Flatten())
model.add(Dense(128, 'relu'))
model.add(Dense(10, 'softmax'))

In [25]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv3d_5 (Conv3D)           (None, 14, 14, 14, 32)    896       
                                                                 
 conv3d_6 (Conv3D)           (None, 12, 12, 12, 32)    27680     
                                                                 
 max_pooling3d_3 (MaxPooling  (None, 6, 6, 6, 32)      0         
 3D)                                                             
                                                                 
 conv3d_7 (Conv3D)           (None, 4, 4, 4, 32)       27680     
                                                                 
 max_pooling3d_4 (MaxPooling  (None, 2, 2, 2, 32)      0         
 3D)                                                             
                                                                 
 flatten_1 (Flatten)         (None, 256)              

In [26]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/5
313/313 [==============================] - 62s 196ms/step - loss: 1.5562 - accuracy: 0.4551 - val_loss: 1.1692 - val_accuracy: 0.5920
Epoch 2/5
313/313 [==============================] - 55s 177ms/step - loss: 1.0817 - accuracy: 0.6215 - val_loss: 1.0140 - val_accuracy: 0.6460
Epoch 3/5
 64/313 [=====>........................] - ETA: 42s - loss: 0.9265 - accuracy: 0.6699

KeyboardInterrupt: 